### ISSUE TITLE
cannot get access_token by authorization code + PKCE

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#114]
after getting the code via code_challenge from AAC.
trying to get the access token via code and code_verifier AAC returns a "bad credentials" error

I think the issue is in the OAuth2ClientPKCEAuthenticationProvider class, in the following code:

```
            // check if client can authenticate with this scheme
            if (!client.getAuthenticationMethods().contains(authenticationMethod)) {
                this.logger.debug("Failed to authenticate since client can not use scheme " + authenticationMethod);
                throw new BadCredentialsException("invalid authentication");
            }
```

**Comment by gianpaolo-tndigit** [comment]
no, I hadn't configured it.
Now I have configured it and it works!
thank you
![Configurazione per PKCE](https://user-images.githubusercontent.com/100349014/170434652-e6ce886d-5cf8-4bfa-9c25-2b38331de3f6.GIF)

**Comment by matteo-s** [comment]
We definitely need to improve the documentation.
