### ISSUE TITLE
cannot import client from UI

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#143]
if you try to "export" a client configuration and then try to "import", AAC response is "invalid file".
![AAC errore importazione](https://user-images.githubusercontent.com/100349014/174312210-d6b7963c-0183-4c88-9dce-92a6caa17841.jpg)
[clientapp-client_load_test_01.txt](https://github.com/scc-digitalhub/AAC/files/8928182/clientapp-client_load_test_01.txt)
(clientapp-client_load_test_01.txt was renamed from clientapp-client_load_test01.yaml to upload it)

**Comment by matteo-s** [comment]
partial fix via #216 : copy and paste yaml into the UI instead of using upload on windows.
