### ISSUE TITLE
exporting a custom service doesn't work

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#150]
if you try to use the export functionality in the "App and services -> API services" menu, it returns an error.
AAC redirect to "https://localhost:8080/console/dev/services/realm_load_test/s_287054a922a349ec94c2af843bc7617b/yaml"
By changing the address in the address bar to "https://localhost:8080/console/dev/services/realm_load_test/s_287054a922a349ec94c2af843bc7617b/export" you can export the file.

**Comment by matteo-s** [comment]
closed with  #216
