### ISSUE TITLE
newly added duplicated API scopes are silently removed from previous service 

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#151]
requirements:
custom API service (a) with a **read:profile** scope
custom API service (b) without scopes

if you try to add the **read:profile** scope to service (b) it is "removed" from service (a) and added to (b) without indicating that the **read:profile** scope is already present in service (a)

**Comment by matteo-s** [comment]
This exact behavior is a bug: adding scopes with the same definition as currently existing scopes in another service should be blocked.
Besides, the current implementation has a system wide registry of scopes, which effectively blocks realm administrators in using scopes already registered in another realm.
