### ISSUE TITLE
Error obtaining access token with POST 'application/x-www-form-urlencoded;charset=UTF-8' 

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#245]
#242 
using the autorizzation_code flow with client id and secret and also with PKCE via postman.
set the correct user and password aac fails and returns the following error without getting the token:

ERROR 6236 --- [nio-8080-exec-9] i.s.aac.oauth.endpoint.TokenEndpoint     : Error: Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported
WARN 6236 --- [nio-8080-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported]

here the raw call from postman:
POST /oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic XXX 
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Cache-Control: no-cache
Postman-Token: 28a6d2d0-3c37-4add-9c08-5aea4f24b3f1
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 211
 
grant_type=authorization_code&code=Zi7jaQFEOVUKI4rmqPkHAjpUBjE&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&code_verifier=B_bGFpg1K358Rlkba8Q-8VhnjVBGU4pdiKQQkx4lTcc&client_id=c_0afc5b9b45ea47ad890a7cbb453c69e4
 
HTTP/1.1 500 Internal Server Error
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Cache-Control: no-store
Pragma: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 14 Sep 2022 13:00:18 GMT
Connection: close
 
{"error":"server_error","error_description":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"}

**Comment by matteo-s** [comment]
regression from here
https://github.com/scc-digitalhub/AAC/blame/23942dd284fdc0ea23347f8f6a0817ca93992595/src/main/java/it/smartcommunitylab/aac/oauth/endpoint/TokenEndpoint.java#L85

parameters should be obtained via RequestParam
