### ISSUE TITLE
cannot export client from UI

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#261]
pressing the export button from the interface does not export the file, it does not return any errors even in the console.
Maybe it's a problem with javascript?

if you use the link the url bar, it works:

- console/dev/realms/{realm}/apps/{client_id}

![image](https://user-images.githubusercontent.com/100349014/193290448-cd3abc2c-3b10-4e72-acad-f8e5292722ed.png)

**Comment by matteo-s** [comment]
fix with b20e4ef
