### ISSUE TITLE
UI Accounts user visibility problem #1

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#285]
after sending a verification email to a newly invited user, the interface changes and the actions are no longer working and it is necessary to go back and re-enter in the user Accounts to resolve.

to create the problem:

1. invite a user
2. enter the Accounts user
3. press verify

the interface changes view

**Comment by matteo-s** [comment]
Can't reproduce. Btw "verify" sends the verification mail, while "confirm" confirms the user mail.
So when you click verify you will reset the confirmation status to `false` and then send a mail.
This will change the view accordingly.
