### ISSUE TITLE
problem with SAML authentication

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#291]
- branch external-repositories

does not perform the first SAML request

the URL it tries to use:
http://localhost:8080/auth/samlauthenticate

it usually was: 
http://localhost:8080/auth/saml/authenticate

**Comment by matteo-s** [comment]
There is a missing slash in the url built by the provider...
```
    @Override
    public String getAuthenticationUrl() {
        // TODO build a realm-bound url, need updates on filters
        return "/auth/" + getAuthority() + "authenticate/" + getProvider();
    }
```

**Comment by gianpaolo-tndigit** [comment]
when you change this, hangs and does not generate a SAML request:

- org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value '{KdwvZm05nqttjzEBLCzRxqLdohn66bE_UeEfVYvWfh4==org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticationRequestContext@496fb17a}'; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticationRequestContext
- Caused by: java.io.NotSerializableException: org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticationRequestContext
- 2023-01-19 09:52:29.095 ERROR 1220 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

maybe is not linked, but there is also a TemplateInputException

- org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/error.html]")
- Caused by: org.attoparser.ParseException: An error happened during template rendering
- Caused by: org.thymeleaf.exceptions.TemplateOutputException: An error happened during template rendering
- 2023-01-19 09:52:29.097 ERROR 1220 --- [nio-8080-exec-4] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]
