### ISSUE TITLE
support mail configuration without username / password

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#292]
sometimes you don't need to configure the SMTP server with username nor password in the class it.smartcommunitylab.aac.utils.MailService always set them

I suggest to change it like that:

    public void init() throws IOException {
        mailSender.setHost(mailHost);
        mailSender.setPort(mailPort);
        mailSender.setProtocol(mailProtocol);
        if(mailPwd==null || mailPwd.trim().compareTo("")==0) {       	
        	logger.trace("SMTP password is blank, username and password are not set");
        } else {
        	logger.trace("SMTP password is not blank, setting username and password");
            mailSender.setPassword(mailPwd);
            mailSender.setUsername(mailUser);        	
        }

        Properties props = new Properties();
        props.load(mailProps.getInputStream());
        mailSender.setJavaMailProperties(props);

    }

**Comment by matteo-s** [comment]
looks good. Please make a pull request, from 4.x

**Comment by matteo-s** [comment]
closed with #305
