### ISSUE TITLE
SAML authentication: error loading authentication back from spring session

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#296]
- branch 4.x

AAC cannot de-serialize authenticationContext from SAML response

https://github.com/scc-digitalhub/AAC/blob/23942dd284fdc0ea23347f8f6a0817ca93992595/src/main/java/it/smartcommunitylab/aac/saml/auth/SamlWebSsoAuthenticationFilter.java#L149

error:

it.smartcommunitylab.aac.saml.auth.SamlWebSsoAuthenticationFilter.attemptAuthentication
org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticationException: Wrong destination for response
	at it.smartcommunitylab.aac.saml.auth.SamlWebSsoAuthenticationFilter.attemptAuthentication(SamlWebSsoAuthenticationFilter.java:155) ~[classes/:na]

**Comment by matteo-s** [comment]
The linked file does not match current 4.x branch.
After 8783cfa71d9dac776d62867b1b8bd1eaf207d1fe we use another request context.
Please check the version.

See https://github.com/scc-digitalhub/AAC/blob/8783cfa71d9dac776d62867b1b8bd1eaf207d1fe/src/main/java/it/smartcommunitylab/aac/saml/auth/SamlWebSsoAuthenticationFilter.java#L149

**Comment by gianpaolo-tndigit** [comment]
that the line where AAC hangs, I also check the commit https://github.com/scc-digitalhub/AAC/commit/8783cfa71d9dac776d62867b1b8bd1eaf207d1fe from git log 

that's the line in the 4.x code

https://github.com/scc-digitalhub/AAC/blob/8783cfa71d9dac776d62867b1b8bd1eaf207d1fe/src/main/java/it/smartcommunitylab/aac/saml/auth/SamlWebSsoAuthenticationFilter.java#L149

**Comment by gianpaolo-tndigit** [comment]
hoping it will help:

https://stackoverflow.com/questions/72508155/spring-saml2-and-spring-session-savedrequest-not-retrieved-cannot-redirect-to

I try to change SameSite cookie value from Lax to None and it's works.
