### ISSUE TITLE
UI problem with user console building

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#315]
tryng executing mvn spring-boot:run -X got these messages:

(full log in TXT)
[error-user-console.txt](https://github.com/scc-digitalhub/AAC/files/10805318/error-user-console.txt)

[INFO] --- frontend-maven-plugin:1.12.1:yarn (user console build) @ aac ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:1.12.1:yarn from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:1.12.1, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:1.12.1:yarn' with basic configurator -->
[DEBUG]   (f) arguments = dist
[DEBUG]   (f) installDirectory = C:\Users\TD671\aac-workspace\aac-console\target
[DEBUG]   (f) project = MavenProject: it.smartcommunitylab:aac:4.2.0-SNAPSHOT @ C:\Users\TD671\aac-workspace\aac-console\pom.xml
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@43982337
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@fe34b86
[DEBUG]   (f) skipTests = false
[DEBUG]   (f) testFailureIgnore = false
[DEBUG]   (f) workingDirectory = C:\Users\TD671\aac-workspace\aac-console\user-console
[DEBUG]   (f) yarnInheritsProxyConfigFromMaven = true
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:1.12.1:yarn {execution: user console build}
[DEBUG] -- end configuration --
[INFO] Running 'yarn dist' in C:\Users\TD671\aac-workspace\aac-console\user-console
[DEBUG] Executing command li
ne [C:\Users\TD671\aac-workspace\aac-console\target\node\yarn\dist\bin\yarn.cmd, dist]
[INFO] yarn run v1.21.1
[INFO] $ react-scripts build && gzipper c --gzip --brotli --remove-larger --skip-compressed ./build
[INFO] Creating an optimized production build...
[INFO] Failed to compile.
[INFO]
[INFO] [eslint]
[INFO] src\App.tsx
[INFO]   Line 1:20:    Delete `â??`  prettier/prettier
[INFO]   Line 2:75:    Delete `â??`  prettier/prettier
....
....
INFO]
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] error Command failed with exit code 1.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:48 min
[INFO] Finished at: 2023-02-22T16:09:11+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (user console build) on project aac: Failed to run task: 'yarn dist' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (user console build) on project aac: Failed to run task
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:306)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
....
   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by matteo-s** [comment]
Looks like you've got an encoding issue. The linter finds some unexpected character in files, which usually is a sign that you are reading UTF-8 with a different charset.
Given that this is on Windows my guess is you are using the windows charset in place of UTF.  
Try to fix the encoding on your side, maybe by configuring node environment or the editor .
Or use linux.
