### ISSUE TITLE
cannot retrieve access token from postman

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#317]
trying to get the token via postman (get new access token)
after entering username and password AAC hangs

client configuration:
[clientapp-client_manager.txt](https://github.com/scc-digitalhub/AAC/files/10826327/clientapp-client_manager.txt)

get postman:
GET http://localhost:8080/oauth/authorize?response_type=code&client_id=c_aec7a6dc317a41c6a2a606e9426fe3cb&state=openid%20profile%20email&scope=openid%20profile%20email&redirect_uri=http%3A%2F%2Flocalhost%3A8080&code_challenge=4yaMp7fTgPwsf3JwsNnw46ZgYwOj-0z6w6eztZ3IaRw&code_challenge_method=S256
500
Request Headers
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/10.10.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:8080/-/realm_test/login?client_id=c_aec7a6dc317a41c6a2a606e9426fe3cb
Accept-Encoding: gzip, deflate, br
Accept-Language: it
Cookie: SESSION=ODc4NTVlODUtMmEzZC00ODRlLWFkYmItOTFkY2IwOTdlYjYz
Response Headers
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: close
Content-Language: en
Content-Length: 1297
Content-Type: text/html;charset=UTF-8
Date: Fri, 24 Feb 2023 16:22:59 GMT
Expires: 0
Location: http://localhost:8080?code=K12ZH0dwzzv2p-p2TZWafn2VVy8&iss=http://localhost:8080&state=openid%20profile%20email
Pragma: no-cache
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

error log:
2023-02-24 16:50:13.322 ERROR 10812 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value 'it.smartcommunitylab.aac.oauth.store.InMemoryAuthorizationRequestStore@5a1e2330'; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [it.smartcommunitylab.aac.oauth.store.InMemoryAuthorizationRequestStore]

**Comment by matteo-s** [comment]
Please export client config as yaml and attach.

**Comment by gianpaolo-tndigit** [comment]
that is client yaml

[clientapp-client_manager.yaml.txt](https://github.com/scc-digitalhub/AAC/files/10838417/clientapp-client_manager.yaml.txt)

thats is realm backup yaml

[realm-realm_test-config.yaml.txt](https://github.com/scc-digitalhub/AAC/files/10838393/realm-realm_test-config.yaml.txt)
