### ISSUE TITLE
actuator probe: liveness and readiness are not accessible

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#328]
you cannot access probe by wget nor k8s probes:

wget http://localhost:8081/actuator/health/liveness
wget http://localhost:8081/actuator/health/readiness

AAC redirect you on login page with a 404.

from MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE you have:
health, liveness, readiness

But actuator of spring create these endpoints:

- health
- health/liveness
- health/readiness

The filter in it.smartcommunitylab.aac.config.MonitoringSecurityConfig.java blocks this path cause it create a filter like that

- health
- liveness
- readiness

but wget http://localhost:8081/actuator/liveness does not give you any information.

**Comment by matteo-s** [comment]
There are no liveness nor readiness probes in AAC. We could add some.
You can enable (on kubernetes) the probes from spring boot, but they won't expose additional info than /health.

Anyway, if you want to change the actuator configuration you should check the docs to provide a valid setting.
https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/actuator.html#actuator.endpoints.exposing

liveness and readiness are not endpoints, so you can not set them this way. 
```
from MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE you have:
health, liveness, readiness
```
Only `health` is a valid endpoint: liveness and readiness, when enabled, are exposed on /health endpoint, and additionally as groups.

By default, in AAC actuator endpoints are exposed on a management port, on the root context.
So addresses do not have `/actuator/` prefix, for example:
 
```
/health
/health/liveness
/health/readiness

```

If you want to see the details of the probes on `\health` you should set `management.endpoint.health.show-details` and `management.endpoint.health.show-components` to `always` 

https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/actuator.html#actuator.endpoints.health

If you want access to subgroups for health we need to modify the security filter, and add subpaths to the antMatcher.

```
        List<RequestMatcher> endpointMatchers = Arrays.stream(endpoints)
                .map(u -> new AntPathRequestMatcher(basePath + "/" + u + "/**"))
                .collect(Collectors.toList());
```
