### ISSUE TITLE
OIDC Rp endsession POST not supported

### ISSUE THREAD

**Issue by matteo-s** [scc-digitalhub/AAC#360]
As per spec, RP-Initiated logout should be exposed both for GET and POST.
AAC uses the `/endsession` endpoint for 
* GET -> serving the page 
* POST -> form action from page

we need to move the action to another path and expose `POST /endession` as per spec

**Comment by gianpaolo-tndigit** [comment]
close with https://github.com/scc-digitalhub/AAC/pull/425
