### ISSUE TITLE
cannot retrieve realm statistics and configuration overview

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#422]
In realm system is not possible to retrieve cannot retrieve realm statistics and configuration overview

AAC Hangs with:

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT event_time, principal, realm, event_type, event_data FROM audit_events WHERE realm = ? AND event_type = ? AND event_time >= ? ORDER BY event_time DESC]; nested exception is org.postgresql.util.PSQLException: Colonna denominata «event» non è presente in questo «ResultSet».

![image](https://github.com/scc-digitalhub/AAC/assets/100349014/ce71437b-1251-4de9-92e0-29f4ca575410)

**Comment by matteo-s** [comment]
fix by cd037ab906972b9fb79cefd8507df24f398e3d4e
