### ISSUE TITLE
code_challenge_methods_supported is exposed only in OAUTH well-known

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#435]
AAC support two URLs for discovery:

- .well-known/oauth-authorization-server
- .well-known/openid-configuration

but code_challenge_methods_supported is exposed only in .well-known/oauth-authorization-server

why is not exposed also in .well-known/openid-configuration?

**Comment by matteo-s** [comment]
OAuth 2.0 Authorization Server Metadata https://www.rfc-editor.org/rfc/rfc8414.html specifies the content for `.well-known/oauth-authorization-server`.

`code_challenge_methods_supported` is described in that RFC, and is correctly included in the metadata.

OpenID Connect Discovery 1.0 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
instead does not mention any such parameter, so anything outside that spec is currently not included  in `.well-known/openid-configuration`.

Anyway, given that the spec says 
```
Additional OpenID Provider Metadata parameters MAY also be used. Some are defined by other specifications, such as OpenID Connect Session Management 1.0 (https://openid.net/specs/openid-connect-discovery-1_0.html#OpenID.Session).
```

we could add all the OAuth2 metadata to the same document, without violating the spec.

**Comment by matteo-s** [comment]
closing this in favor of #438
