### ISSUE TITLE
CIE: missing trust_marks paramter in RP metadata

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#469]
according to the example in https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/esempi.html#en-2-1-entity-statement-response

when trust_marks is set does not appear as parameter in metadata trust_marks 

branch: https://github.com/scc-digitalhub/AAC/pull/465

**Comment by matteo-s** [comment]
Can you provide more details?

The example linked does not describe a response an RP (such as AAC) can
provide.
See
https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/federation_endpoint.html


An RP should expose only its own metadata and the resolve endpoint, not a
fetch entity statement





Il mer 27 dic 2023, 17:08 gianpaolo-tndigit ***@***.***> ha
scritto:

**Comment by thomaschiozzi-tndigit** [comment]
Currently, when configuring AAC as an RP in a federation (openidfed), the "Trust Mark" configuration does not appear in the entity configuration/metadata claims exposed at the `./well-known/openid-federation` endpoint, even when it is configured and has non-zero value in the `OpenIdFedIdentityProviderConfigMap` .
According to https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/entity_configuration.html#entity-configuration-foglia-e-intermediari
it is mandatory to include the trust_marks claim in the entity configuration (after they are obtained and set, clearly).
