### ISSUE TITLE
CIE: acr_values not properly formatted in federation authorization request 

### ISSUE THREAD

**Issue by thomaschiozzi-tndigit** [scc-digitalhub/AAC#471]
When performing an authorization request in a openid federation setting, the acr_values claims is current formatted as an array of strings - link to reference code [https://github.com/scc-digitalhub/AAC/blob/3c8f2f414fb30c5fa5de82745a4805e385f64af7/src/main/java/it/smartcommunitylab/aac/openidfed/auth/OpenIdFedOAuth2AuthorizationRequestResolver.java#L269](https://github.com/scc-digitalhub/AAC/blob/3c8f2f414fb30c5fa5de82745a4805e385f64af7/src/main/java/it/smartcommunitylab/aac/openidfed/auth/OpenIdFedOAuth2AuthorizationRequestResolver.java#L269) 

According to [OIDC Specs](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) and [CIE Specs](https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/authorization_endpoint.html#request) it should be a "Space-separated string".

**Comment by matteo-s** [comment]
good catch. Given that it should be fixed by a recent commit and there is no test (yet), please check again on the current HEAD.
