### ISSUE TITLE
Birthdate attribute causes exception in token creation

### ISSUE THREAD

**Issue by elisanp** [scc-digitalhub/AAC#486]
As of commit 2bab5cd65956063a65e700434abd81d0c21b0a49, when requesting a token with scope `profile` the following error occurs if the user attributes birthdate exists in the authentication context and it is formatted as `yyyy-MM-dd`:

`ERROR i.s.aac.console.ConsoleExceptionHandler: error processing request: Java 8 date/time type java.time.LocalDate not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: it.smartcommunitylab.aac.profiles.model.OpenIdProfile["birthdate"])`

**Comment by matteo-s** [comment]
should be close via 229f7db
