### ISSUE TITLE
OIDC-Fed Authentication request - url encoded message

### ISSUE THREAD

**Issue by pietrodematteis** [scc-digitalhub/AAC#488]
Into Authentication request some claims like client_id and redirect_uri are not url encoded.
Seems a problem linked to Spring
https://github.com/spring-projects/spring-security/issues/9170

**Comment by matteo-s** [comment]
I double checked with the spec and url are indeed encoded properly by Spring.

https://datatracker.ietf.org/doc/html/rfc3986#section-3.4
```
   query       = *( pchar / "/" / "?" )
   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

Closing this. If you have additional info feel free to comment and reopen.
