### ISSUE TITLE
Routing Exceptions might induce Spring whitelabel error page

### ISSUE THREAD

**Issue by thomaschiozzi-tndigit** [scc-digitalhub/AAC#530]
Some exceptions might induce some amount of information discolusure or in general provides an undesirable user experience due to the default that they trigger a default or whitelabel error page.
As far as I know, this behaviour was only discovered when making malfored requests. For example the following page is returned when making a request to `/console/dev/realms/system/users?{` due to the fact that it contains the character `{` .

![image](https://github.com/scc-digitalhub/AAC/assets/144908950/f179f15e-0acb-4925-a998-5961ae6c7f5d)

**Comment by matteo-s** [comment]
That is not the whitelabel error page but the tomcat error page, and is served by tomcat outside the application.
Given that it is not handled by AAC we should investigate tomcat configuration in order to either disable the default error pages or replace it with a static html page.

**Comment by thomaschiozzi-tndigit** [comment]
Including additional information for future reference and general insight. The following open issue in the Spring project discusses this very same problem

https://github.com/spring-projects/spring-boot/issues/21257

It appears that Spring does not offer any configuration for `application.*` file that manages this problem.
If I understand correctly, it appears that the suggested approach is to override the default configuration of the embedded tomcat server inside spring.

**Comment by matteo-s** [comment]
Yes, as far as I know that is the only way. If you want to, try it in a branch.\
I'm fine with a blank error page + logging.

**Comment by thomaschiozzi-tndigit** [comment]
If information discolsure is the primary concern, it appears that the Spring application property `server.error.include-stacktrace: never` suffices to minimize the amount of information included in the tomcat error page.
Se picture below, produced by a request with a malformed URL (as it includes the `{` character).

![image](https://github.com/scc-digitalhub/AAC/assets/144908950/e932b8e5-02a6-48f0-b2ff-7660b5f554bb)

**Comment by matteo-s** [comment]
closed with #536
