### ISSUE TITLE
Userinfo endpoint returns inconsistent claims

### ISSUE THREAD

**Issue by thomaschiozzi-tndigit** [scc-digitalhub/AAC#544]
If a user has multiple accounts (say, 2 acocunts from different identity providers linked via mail), after he retrieves an access token he can presents it to the userinfo endpoint to get his claims
`curl --request GET \
--url 'AAC_SERVER/userinfo' \
--header 'content-type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer ACCESS_TOKEN' `

However, the result of this HTTP request is not deterministic, as in, making the subsequent request multiple times (even in a short time span) possibly yields different results. Sometimes the returned claims are extracted from the first account, other times they are extracted from the second account.
Is this the expected behaviour? If not, what should be the expected behaviour?

EDIT: upon closer inspection, the non deterministic behaviour might (eventually...) be reduced to this function call
https://github.com/scc-digitalhub/AAC/blob/115ac576bbd1eaed75326711b32720cdd9f497e8/src/main/java/it/smartcommunitylab/aac/claims/DefaultClaimsService.java#L167
"realized" (after a few calls) by
https://github.com/scc-digitalhub/AAC/blob/115ac576bbd1eaed75326711b32720cdd9f497e8/src/main/java/it/smartcommunitylab/aac/profiles/extractor/OpenIdProfileExtractor.java#L45-L59

When making an `/userinfo` request, the identity fetched by `UserIdentity id = identities.iterator().next();`  is not consistent among subsequent endpoint calls.

**Comment by matteo-s** [comment]
Yes, the "first" element is not consistent: although the backing list should provide consistent ordering the results via iterator may vary.
An easy fix should be replacing the list (or set) in userDetails with a linkedlist (or linkedhashset).
