### ISSUE TITLE
Openid Federation IdPs with invalid OPs break the login page due to NullPointerException

### ISSUE THREAD

**Issue by thomaschiozzi-tndigit** [scc-digitalhub/AAC#556]
In a realm when there is an openid federation identity provider, if there is an offline of invalid OP in the federation, the whole login page will crash (even if other providers could be available in the federation).

When the login controller obtains the login provider
https://github.com/scc-digitalhub/AAC/blob/e5bbba84a116d783e613fd29b4d0bd6bf230c1ee/src/main/java/it/smartcommunitylab/aac/controller/LoginController.java#L227-L233

in case of the openid federation we loop through each possible OP to add it to the login
https://github.com/scc-digitalhub/AAC/blob/e5bbba84a116d783e613fd29b4d0bd6bf230c1ee/src/main/java/it/smartcommunitylab/aac/openidfed/provider/OpenIdFedIdentityProvider.java#L198-L233

but some those steps might produce a null pointer exception if the OP is offline, has invalid metadata or has other issues.
For example `op` defined in line 208 is null, then line 211 will produce a null pointer exception.

This issue was discovered due to the fact that today (2024-03-04) the CIE federation pre-production environment has an invalid OP metadata and as a consequence the whole realm login page was not usable.

**Comment by matteo-s** [comment]
closed with #557
