### ISSUE TITLE
cannot import Service from "Import" function

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#585]
When attempting to import a service, AAC hangs an issue exception 'File Not Found' from DevServicesController.importRealmService

`
reg = yamlObjectMapper.readValue(file.getInputStream(), Service.class);
`

a possibile solution is: 

    if (multiple) {
        Map<String, List<Service>> list = yamlObjectMapper.readValue(yaml, typeRef);
        for (Service reg : list.get(LIST_KEY)) {
            regs.add(reg);
        }
    } else {
        Service reg;
        if (file != null) {
            // try single element from file
            reg = yamlObjectMapper.readValue(file.getInputStream(), Service.class);
        } else {
            // use obj as single element
            reg = yamlObjectMapper.convertValue(obj, Service.class);
        }
        regs.add(reg);
    }

**Comment by matteo-s** [comment]
I don't fully understand the issue: are you trying to import via file or by pasting a string with the actual content in it?
Because looking at code the only edge case the leads to that exception is when the yaml is NOT read from file (so 'File Not Found' issue), but from string.

**Comment by gianpaolo-tndigit** [comment]
we are encountering the "File Not Found" exception when attempting to import a service via the UI using the IMPORT button. The import process involves pasting a string in YAML format.

From your explanation, it seems the code might be expecting a file input rather than a string, which could be causing the issue.

**Comment by gianpaolo-tndigit** [comment]
solve with #586
