### ISSUE TITLE
Links / Redirecting from server context are not corrects

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#62]
**how to replicate error:**
set the environment variables:

- CONTEXT_SERVER = /aac
- APPLICATION_EXT_URL = http://localhost:8080/aac

we run the project aac with a realm setted (in this example it is realm_citizens )
When configuring access to http://localhost:8080/aac:

- if you try to log in, in a realm the system loses the server context http://localhost:8080/login?realm=realm_citizens I suppose to find http://localhost:8080/aac/login?realm=realm_citizens

- similarly if you try to access the administration console the link is http://localhost:8080/-/system/login instead of http://localhost:8080/aac/-/system/login (see image).

![server-context](https://user-images.githubusercontent.com/100349014/155703392-b844adab-296d-4771-a9a8-bd64f91ad270.gif)

**Comment by matteo-s** [comment]
changing the servlet context is not something we want to support. 
When needed, administrators can always deploy AAC behind a reverse proxy handling their custom mapping.

Instead generated (absolute) links/redirects should always respect APPLICATION_EXT_URL. 
I'll close this as wontfix. Please open a new issue if APPLICATION_EXT_URL is not respected behind a reverse proxy.
