### ISSUE TITLE
activation email is not working for internal users with change password set

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#63]
**how to replicate error:**
run the project aac
go in amministrative mode
create a new user -> the system send and email to activate
if you use the link the system give you an "internal error" and on log you can read:
java.lang.IllegalArgumentException: **userid invalid**
	at it.smartcommunitylab.aac.internal.controller.InternalCredentialsController.changepwd(InternalCredentialsController.java:55) 
so you cannot verify the user

**Comment by matteo-s** [comment]
For users with "change password at next login" set (for example invited users) we redirect after login to changepwd.
The userid passed as parameter to the action contains characters which are invalid for tomcat.
The fix will be included in an update.
