### ISSUE TITLE
make the interface clearer

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#67]
among the possible actions in an identity provider, edit should not be visible.
There should be a view action, or once you enter the edit screen indicate with a message that the changes will not be saved
![edit-provider-disabled](https://user-images.githubusercontent.com/100349014/156318157-ca12fd12-1aa9-4af7-ad4c-e2843d700865.gif)

**Comment by matteo-s** [comment]
Edit is always a valid action. You can edit the configuration but in order to apply it you need to disable+save+enable.
We locked the save button for active providers, a message will probably help administrators understand the flow.
