### ISSUE TITLE
Realm delete works only for empty registrations

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#68]
when you try to delete a realm it gives the error "invalid type" but I think the problem is that
the realm must no longer have identiy providers, users, clients configured before it can be deleted.
rendere più chiaro un messaggio di errore "invalid type"
in fact, if you delete the components in the realm, the realm get deleted with the delete function
![realm_empy_before_delete](https://user-images.githubusercontent.com/100349014/156338471-b22320e5-249a-4a20-a62d-80cdbc08cdad.gif)

**Comment by matteo-s** [comment]
Thanks for the report. The message is generic because there is a bug in the removal.
There is no need to clean up a realm before removing it: everything related should be contextually removed.
This is a bug.
