### ISSUE TITLE
swagger does not redirect correctly

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#69]
**how to replicate error:**

- run the project aac
- go to http://localhost:8080/swagger-ui.html --> AAC Admin API
- Authorize --> oauth2 (OAuth2, authorizationCode)
- type client_secret, client_id, select all scopes  --> button Authorize
- it will prompt the login, login by google authentication then the system give that error "Requested redirect_uri http://localhost:800/swagger-ui/oauth2-redirect.html is not a valid redirect"

I attach the IDP config and client config
[client.txt](https://github.com/scc-digitalhub/AAC/files/8169435/client.txt)
[idp.txt](https://github.com/scc-digitalhub/AAC/files/8169436/idp.txt)
![swagger-richiesta-non-valida](https://user-images.githubusercontent.com/100349014/156358809-f38d1ffa-38a2-43e2-a442-26c07bfe3851.GIF)

**Comment by gianpaolo-tndigit** [comment]
the problem persist also if you don't "select all" scope, but "select none"

**Comment by matteo-s** [comment]
In order to test via swagger you need to register the URL (or at minimum `http://localhost:8080`) as a valid redirect for your application via dev console.

By looking at your config I can't find any redirect registered. Do you have some configured and the export didn't include it, or were you able to save a configuration with `authorization_code` enabled and no redirect?

**Comment by gianpaolo-tndigit** [comment]
I check and i found the "clue":

- in the configuration i sent, the redirect was not set
- i try with http://localhost:8080/* and does not work 
- i try with entire uri http://localhost:8080/swagger-ui/oauth2-redirect.html and WORK

**solution:** 
Add http://localhost:800/swagger-ui/oauth2-redirect.html to OAuth2.0 Configuration of the client you want to use with swagger

**proposel:**
swagger-ui is "internal" maybe could nice have it in configuration by default?
