### ISSUE TITLE
are set of attributes distinct for each realm?

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#71]
in a realm I created an attribute set with identifier **application**.
in another realm I tried to create an attribute set with identifier **application** but it tells me "identifier is not unique" (image1) but I don't see in the list of attribute set in that realm
then I created an attribute set with identifier **application1** and i see in the user profile "scope and resources" (image2)
![insieme-identificatori-doppi](https://user-images.githubusercontent.com/100349014/157833999-84179528-1b94-4b24-844a-36e894094683.gif)
![user-profile-attributes](https://user-images.githubusercontent.com/100349014/157834012-98d06714-c28e-4aa2-b3e5-1a61d5044a65.GIF)

**Comment by matteo-s** [comment]
Attribute sets and services, and subsequently scopes, are shared across all realms. As such, identifiers must be globally unique.
A future version will probably handle this per-realm.
