### ISSUE TITLE
cannot get token by username and password

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#74]
try to get the token from password mode by entering username and password. 
the system give you the error :

- Error: param does not match pattern ^[a-zA-Z0-9_:-]+$.

in OAuth2RequestFactory.createTokenRequest in the code:
```
        if (authorizationGrantType == PASSWORD) {
            String username = readParameter(requestParameters, "username", STRING_PATTERN);
```

**Comment by matteo-s** [comment]
Can you paste the username? Does it match the pattern?

**Comment by gianpaolo-tndigit** [comment]
> Can you paste the username?

the username is: all@dipendente.it

> Does it match the pattern?

 no, cause it contains "." and "@"
