### ISSUE TITLE
Are API /oauth/revoke and /oauth/introspect accessibile for developers?

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#77]
I tried to do a POST call to the API address
http://localhost:8080/oauth/introspect

in the header has been inserted Authorization: Bearer eyJraWQiO ...
in the body application/x-www-form-urlencoded and as a token parameter with the token ID eyJraWQiO ..., as indicated by
https://datatracker.ietf.org/doc/html/rfc7662#section-2

but 401 always remains, same speech with http://localhost:8080/oauth/revoke

Am I doing something wrong?

**Comment by matteo-s** [comment]
As per spec, those endpoints are dedicated to *clients* which are the audience of tokens.
As such, authentication should carry client credentials, while you are trying to insert an oauth access token in the authorization header. See for example https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

To recap: add client credentials as basic auth `clientId:clientSecret` in authorization header. And be sure that the given client is one of the audiences of the token.

Unrelated: please avoid opening issues for this kind of questions, let's keep this for bugs/feature requests etc
