### ISSUE TITLE
change password vulnerability #2

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#93]
when you ask for a password change, the old one is still usable

**Comment by matteo-s** [comment]
Can you elaborate? When you change the password the old one isn't stored, so you can not use it for login.
The current user sessions remain unaffected.

Maybe when you request the `reset` of the password?

**Comment by gianpaolo-tndigit** [comment]
Yes, not when the user ask for password change but when a user requests a password reset.

**Comment by matteo-s** [comment]
Then the current behavior is correct.
If we lock the old password only for reset requests we let malicious users lock anyone out by simply requesting a reset, which would result a denial of service.

Until the user verifies the reset request via code (which is sent via mail), the current password will be active. After providing the reset code, which verifies the user identity, the old password will be removed and the new password set as active.
