### ISSUE TITLE
audit: wrong credentials appears in clear

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#99]
administrator has the ability to view the access logs of users.
If a user fails an authentication, credentials are registered and can be viewed in clear.

**Comment by matteo-s** [comment]
Identity providers have a configurable level of audit:
* minimal: only error information
* details: add exception and web details
* full: add full messages 

Configure a level of DETAILS or MINIMAL to avoid storing requests with username+credentials in audit events.

Related #104
